FROM node:24-bookworm-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM cgr.dev/chainguard/nginx:latest AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps --chown=nonroot:nonroot /app/dist /usr/share/nginx/html
EXPOSE 8080

