FROM node:24-bookworm-slim AS deps
WORKDIR /app
COPY package*.json ./

RUN npm ci --omit=dev

FROM gcr.io/distroless/nodejs24-debian13:nonroot AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps --chown=nonroot:nonroot /app/node_modules ./node_modules

COPY  --chown=nonroot:nonroot src ./src
EXPOSE 5050
CMD ["src/server.js"]

