apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifefit-backend
  labels:
    app: lifefit-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lifefit-backend
  template:
    metadata:
      labels:
        app: lifefit-backend
    spec:
      containers:
        - name:  backend
          image: lifefit-backend:4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
          envFrom:
            - secretRef:
                name: lifefit-db-secret

          volumeMounts:
            - mountPath:  "/app/config"
              readOnly: true
              name: backend-config

      volumes:
        - name: backend-config
          configMap:
            name: lifefit-backend-config