apiVersion: v1
kind: Service
metadata:
  name: lifefit-backend-service
  labels:
    app: lifefit-backend
spec:
  selector:
    app: lifefit-backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP