apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: lifefit-postgres
spec:
  selector:
    app: lifefit-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP